# Generated by Django 6.0.5 on 2026-06-01 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Курсы повышения квалификации', 'Курсы повышения квалификации'), ('Курсы переподготовки', 'Курсы переподготовки'), ('Курсы по охране труда', 'Курсы по охране труда')], max_length=100, verbose_name='Вид курса'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('наличными', 'Наличными'), ('перевод по номеру телефона', 'Перевод по номеру телефона')], max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='application',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Идет обучение', 'Идет обучение'), ('Обучение завершено', 'Обучение завершено')], default='Новая', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='portal.application'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^8\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
